import SwiftUI
import Foundation

/// Real in-app i18n: a singleton observable that re-publishes whenever the user
/// changes the language picker. Strings are looked up by key against per-language
/// dictionaries below. Views subscribe to `LocalizationManager.shared` so they
/// re-render on language change without restarting the app.
///
/// To add a new string:
///   1. Add a key + English value under `englishStrings`.
///   2. Add the same key under `simplifiedChineseStrings` and `traditionalChineseStrings`.
///   3. Use `Text(L("key"))` or `String.localized("key")` from views.
///
/// Missing keys fall back to the English dictionary, then to the raw key — so
/// untranslated surfaces stay readable instead of crashing.
@MainActor
final class LocalizationManager: ObservableObject {
    static let shared = LocalizationManager()

    @Published private(set) var language: OrbitaLanguage

    private init() {
        let stored = UserDefaults.standard.string(forKey: "orbitaLanguageCode")
        self.language = OrbitaLanguage(rawValue: stored ?? "") ?? .english
    }

    func setLanguage(_ code: String) {
        let next = OrbitaLanguage(rawValue: code) ?? .english
        guard next != language else { return }
        language = next
    }

    func string(for key: String) -> String {
        let table: [String: String]
        switch language {
        case .english:
            table = LocalizationCatalog.english
        case .simplifiedChinese:
            table = LocalizationCatalog.simplifiedChinese
        case .traditionalChinese:
            table = LocalizationCatalog.traditionalChinese
        }
        if let value = table[key] {
            return value
        }
        return LocalizationCatalog.english[key] ?? key
    }
}

/// Convenience for `Text(L("settings.title"))` at call sites.
@MainActor
func L(_ key: String) -> String {
    LocalizationManager.shared.string(for: key)
}

extension String {
    @MainActor
    static func localized(_ key: String) -> String {
        LocalizationManager.shared.string(for: key)
    }
}

/// Marker modifier for a subtree that contains localized content. It observes the
/// language manager but deliberately does NOT re-key the subtree's identity: a
/// `.id(language)` rebuild used to refresh strings, but it also tore down and
/// recreated the whole subtree on every language switch, resetting local `@State`
/// (selection, scroll position, expanded groups). Instead, each view that calls
/// `L(...)` observes `LocalizationManager.shared` itself (the established
/// `@ObservedObject private var localization = .shared` idiom), so strings refresh
/// in place via normal dependency tracking while state survives the switch.
struct LocalizedModifier: ViewModifier {
    @ObservedObject private var manager = LocalizationManager.shared

    func body(content: Content) -> some View {
        // Touch `language` so this modifier re-evaluates on change without altering
        // identity; descendants refresh through their own observation, not a rebuild.
        _ = manager.language
        return content
    }
}

extension View {
    func localized() -> some View {
        modifier(LocalizedModifier())
    }
}

enum LocalizationCatalog {
    static let english: [String: String] = [
        "onboarding.action.fork.title": "Fork",

        // === i18n second pass (enum/display/store leftovers) ===
        "risk.info": "Metadata only",
        "risk.read": "Reads files",
        "risk.write": "Writes files",
        "risk.exec": "Runs commands",
        "risk.network": "Network access",
        "risk.secret": "Secrets/env",
        "risk.global": "Global scope",
        "applyAction.merge": "Merge into .agents",
        "applyAction.rollback": "Rollback",
        "applyAction.clean": "Clean",
        "op.readSource": "Read source",
        "op.createDirectory": "Create folder",
        "op.createSymlink": "Create link",
        "op.copyPath": "Copy path",
        "op.cachePath": "Cache source",
        "op.restorePath": "Restore source",
        "op.removePath": "Remove path",
        "op.writeFile": "Write file",
        "op.appendLog": "Append log",
        "category.all": "All",
        "category.plugins": "Plugins",
        "category.skills": "Skills",
        "category.agents": "Agents",
        "category.commands": "Commands",
        "category.mcp": "MCP",
        "category.hooks": "Hooks",
        "category.instructions": "Instructions",
        "sort.modified": "Modified",
        "status.enabled": "Enabled",
        "status.disabled": "Disabled",
        "status.broken": "Broken",
        "status.needsAttention": "Needs attention",
        "status.reviewNeeded": "Review needed",
        "status.duplicate": "Duplicate",
        "type.plugin": "Plugin",
        "type.skill": "Skill",
        "type.agent": "Agent",
        "type.mcp": "MCP",
        "type.rule": "Rule",
        "type.instruction": "Instruction",
        "type.hook": "Hook",
        "type.command": "Command",
        "type.unknown": "Unknown",
        "source.packages.lower": "package",
        "source.project.lower": "project",
        "source.packages": "Packages",
        "source.project": "Project",
        "source.other": "Other",
        "scope.thisMac": "This Mac",
        "scope.openProject": "Open a project",
        "scan.neverRefreshed": "Never refreshed",
        "scan.lastRefresh": "Last refresh %@",
        "scan.usingCachedSnapshot": "Using cached snapshot",
        "scan.refreshingCachedSnapshot": "Refreshing cached snapshot",
        "scan.foundCapabilities": "Found %d capabilities",
        "scan.preparing": "Preparing %@",
        "scan.checkingInstructions": "Checking project instructions",
        "scan.checkingCodex": "Checking Codex",
        "scan.checkingClaude": "Checking Claude Code",
        "scan.checkingRules": "Checking project rules",
        "scan.checkingMCP": "Checking MCP",
        "scan.checkingAgents": "Checking .agents",
        "scan.scanningSkills": "Scanning skills",
        "scan.scannedSkillsCount": "Scanned skills - %d found",
        "scan.scannedSkills": "Scanned skills",
        "scan.finishing": "Finishing scan",
        "apply.failure.failedAt": "Failed at: %@.",
        "apply.failure.alreadyApplied": "%d operation(s) had already applied.",
        "apply.failure.notAttempted": "%d operation(s) were not attempted.",
        "app.menu.checkForUpdates": "Check for Updates...",
        "onboarding.tile.skill": "skill",
        "onboarding.tile.rule": "rule",
        "main.markdownPreview.back": "Back",
        "markdown.preview.engine": "Markdown",
        "settings.release.buildFor": "Build %@ for %@",

        // === i18n full-coverage (home-side views) — auto-generated ===
        "main.loading.scanning": "Scanning %@",
        "main.error.unableToScan": "Unable to scan",
        "main.summary.total": "Total",
        "main.summary.plugins": "Plugins",
        "main.summary.skills": "Skills",
        "main.summary.agents": "Agents",
        "main.summary.commands": "Commands",
        "main.summary.hooks": "Hooks",
        "main.loading.percent": "%d%%",
        "main.refresh.refreshing": "Refreshing...",
        "main.macScope.show": "Show This Mac",
        "main.macScope.hide": "Hide This Mac",
        "main.macScope.show.help": "Show capabilities that come from This Mac",
        "main.macScope.hide.help": "Hide capabilities that come from This Mac",
        "main.filter.addAgent": "Add coding agent",
        "main.filter.overview": "Overview",
        "main.menu.pinToTop": "Pin to Top",
        "main.menu.delete": "Delete",
        "main.filter.hideCategories": "Hide categories",
        "main.menu.hide": "Hide",
        "main.chip.dragToReorder": "Drag to reorder",
        "main.empty.noCapabilities": "No capabilities",
        "main.empty.noSearchResults": "No matches for “%@”",
        "main.empty.noFilterResults": "No capabilities match the selected filters",
        "main.search.placeholder": "Search capabilities",
        "main.search.clear": "Clear search",
        "main.summary.risky": "Risky",
        "main.filter.flags.help": "Show only capabilities with the selected flags",
        "main.filter.clearFlags": "Clear",
        "main.flag.broken": "Broken",
        "main.flag.drifted": "Drifted",
        "main.flag.shadowed": "Shadowed",
        "main.flag.risky": "Risky",
        "main.flag.disabled": "Disabled",
        "bulk.groupName": "%@ selected",
        "bulk.selected": "%@ selected",
        "bulk.enable": "Enable",
        "bulk.disable": "Disable",
        "bulk.delete": "Delete",
        "bulk.clear": "Clear selection",
        "bulk.hint": "⌘-click or ⇧-click tiles to select multiple",
        "main.empty.openProject.title": "Open a project",
        "main.empty.openProject.subtitle": "Choose a repository to inspect local coding-agent capabilities.",
        "main.empty.openProject.button": "Open Project...",
        "inspector.field.scope": "Scope",
        "inspector.field.status": "Status",
        "inspector.field.version": "Version",
        "inspector.field.access": "Access",
        "inspector.field.source": "Source",
        "inspector.field.canon": "Canon",
        "inspector.field.agents": "Agents",
        "inspector.field.lock": "Lock",
        "inspector.field.ref": "Ref",
        "inspector.field.skill": "Skill",
        "inspector.field.hash": "Hash",
        "inspector.field.children": "Children",
        "inspector.delete.cancel": "Cancel",
        "inspector.action.delete": "Delete",
        "inspector.delete.title": "Delete %@?",
        "inspector.delete.subtitle": "Native plugin action",
        "inspector.delete.permanent.title": "Permanent delete",
        "inspector.delete.permanent.detail": "This removes the selected capability through its native lifecycle command. The list will update immediately; if the command fails, Orbita will restore the previous state.",
        "inspector.command.label": "Command",
        "inspector.empty.title": "No Selection",
        "inspector.empty.subtitle": "Select a capability to inspect source, scope, access, and loading path.",
        "inspector.action.running": "Running",
        "inspector.action.enable": "Enable",
        "inspector.action.disable": "Disable",
        "inspector.action.hide": "Hide inspector",
        "inspector.native.managerFallback": "plugin",
        "inspector.native.newVersion": "New version available %@",
        "inspector.section.skillsCLI": "Skills CLI",
        "inspector.section.nativePlugin": "Native Plugin",
        "inspector.version.current": "Current",
        "inspector.version.unknown": "Unknown",
        "inspector.version.latest": "Latest",
        "inspector.result.failed.title": "%@ failed",
        "inspector.result.failed.detail": "The command failed before returning readable plugin details.",
        "inspector.result.installed.title": "Installed",
        "inspector.result.installed.detail": "%@ was installed from its Skills CLI lock source.",
        "inspector.result.enabled.title": "Enabled",
        "inspector.result.enabled.detail": "%@ is enabled. Restart the host app if it does not pick up the change immediately.",
        "inspector.result.disabled.title": "Disabled",
        "inspector.result.disabled.detail": "%@ is disabled. Restart the host app if it does not pick up the change immediately.",
        "inspector.result.deleted.title": "Deleted",
        "inspector.result.deleted.detail": "%@ was deleted. Restart the host app if it does not pick up the change immediately.",
        "inspector.result.updateAvailable.title": "Update available",
        "inspector.result.updateAvailable.detail": "%@ can move from %@ to %@. Use Update to apply it.",
        "inspector.result.checked.title": "Checked",
        "inspector.result.canMove.detail": "%@ can move from %@ to %@.",
        "inspector.result.isChecked.detail": "%@ is checked.",
        "inspector.version.unknown.lower": "unknown",
        "inspector.result.checked.noVersion": "The plugin command completed, but did not return version details for this plugin.",
        "inspector.result.updated.title": "Updated",
        "inspector.result.updated.detail": "%@ moved from %@ to %@. Restart the host app if it does not pick up the new version immediately.",
        "inspector.result.upToDate.title": "Already up to date",
        "inspector.result.upToDate.detail": "%@ is already on the latest available version.",
        "inspector.result.updateCompleted.title": "Update completed",
        "inspector.result.updateCompleted.detail": "%@ was updated. Restart the host app if it does not pick up the change immediately.",
        "inspector.action.reinstall": "Reinstall",
        "inspector.action.update": "Update",
        "inspector.dot.broken": "Broken",
        "inspector.dot.needsAttention": "Needs attention",
        "inspector.dot.reviewNeeded": "Review needed",
        "inspector.dot.ready": "Ready",
        "inspector.reason.broken.title": "Broken source",
        "inspector.reason.broken.detail": "Orbita found a record for this capability, but the source path is missing, unreadable, or could not be resolved.",
        "inspector.reason.shadowed.title": "Overridden by a higher-priority scope",
        "inspector.reason.shadowed.detail": "Another capability with the same type and name exists in a higher-priority scope. Priority is project, user, installed, then environment.",
        "inspector.reason.drift.title": "Drift detected",
        "inspector.reason.risky.title": "Access needs review",
        "inspector.reason.risky.detail": "This capability requests %@.",
        "inspector.reason.disabled.title": "Disabled",
        "inspector.reason.disabledCodex.title": "Disabled for Codex",
        "inspector.reason.duplicate.title": "Duplicate name",
        "inspector.reason.ready.title": "Ready",
        "inspector.reason.ready.detail": "Orbita found this capability and did not detect broken links, drift, overrides, or review flags.",
        "inspector.drift.detail": "A capability with the same type and name exists in multiple places, and the content hash is different.",
        "inspector.drift.guidance": "Pick one location as the single source of truth, then symlink or remove the other copies so every agent loads the same version.",
        "inspector.drift.guidance.title": "How to resolve",
        "inspector.drift.location.current": "This tile",
        "inspector.drift.location.differs": "Content differs",
        "inspector.drift.locations.intro": "This capability exists in %@ places and their contents no longer match:",
        "inspector.drift.locations.title": "Where it drifted",
        "inspector.drift.summary": "Found %@ copies whose content no longer matches.",
        "scope.environment": "Environment",
        "scope.installed": "Installed",
        "scope.project": "Project",
        "scope.user": "User",
        "inspector.duplicate.detail": "Orbita found more than one capability with this type and name.",
        "inspector.disabled.byManager": "%@ marks this plugin as disabled.",
        "inspector.disabled.byManifest": "The .agents manifest marks this capability as disabled.",
        "inspector.disabled.codexSkill": "Codex config disables this SKILL.md path in %@. Other agents may still load the same file.",
        "inspector.field.value.placeholder": "-",
        "inspector.markdown.title": "Markdown Preview",
        "inspector.markdown.preview": "Preview",
        "inspector.markdown.openFull": "Open full Markdown preview",
        "inspector.markdown.loading": "Loading preview",
        "inspector.markdown.unavailable": "No markdown preview available.",
        "inspector.source.openFolder": "Open source folder",
        "inspector.markdown.readError": "Unable to read markdown: %@",
        "inspector.markdown.truncated": "Preview truncated.",
        "sheet.addagent.field.source": "Agent source",
        "sheet.addagent.field.displayname": "Display name",
        "sheet.action.cancel": "Cancel",
        "sheet.action.add": "Add",
        "sheet.addagent.preset.custom": "Custom",
        "sheet.addagent.field.name.placeholder": "Agent name",
        "sheet.addagent.field.capabilitymodel": "Capability model",
        "sheet.addagent.preset.manualview": "Manual capability view",
        "sheet.addagent.noglobalpath": "No global path",
        "sheet.addagent.header.title": "Add Coding Agent",
        "sheet.addagent.header.subtitle": "Preset or custom capability view",
        "sheet.addagent.scheme.generic": "Generic",
        "sheet.addagent.scheme.default": "Default",
        "sheet.addagent.scheme.note": "Your custom tool uses the default scheme — all enabled capabilities are shown. Agent-specific schemes (Codex/Claude visibility rules) aren't configured here yet.",
        "sheet.addagent.skillspaths.title": "Skills CLI install paths",
        "sheet.addagent.skillspaths.shared": "Shared",
        "sheet.addagent.skillspaths.dedicated": "Dedicated",
        "sheet.sync.title": "Sync to Agent",
        "sheet.action.sync": "Sync",
        "sheet.sync.step.destination": "Destination",
        "sheet.sync.destination.syncto": "Sync to %@",
        "sheet.sync.destination.choose": "Choose an agent",
        "sheet.sync.step.method": "Method",
        "sheet.sync.method.copy": "Copy",
        "sheet.sync.method.copy.detail": "Create an independent file at the target.",
        "sheet.sync.method.symlink": "Symlink",
        "sheet.sync.method.symlink.detail": "Point the target back to this source.",
        "sheet.sync.step.location": "Location",
        "sheet.sync.preview.agent": "Agent",
        "sheet.sync.status.choose": "Choose a destination agent.",
        "sheet.sync.status.alreadyhas": "%@ already has this capability.",
        "sheet.sync.status.ready": "Ready to sync to %@.",
        "sheet.sync.row.alreadyavailable": "Already available",
        "sheet.sync.row.availabletarget": "Available target",
        "sheet.sync.summary.copy.title": "Copies are independent",
        "sheet.sync.summary.symlink.title": "Symlinks follow the source",
        "sheet.sync.summary.copy.detail": "Future edits to the original will not update this target automatically.",
        "sheet.sync.summary.symlink.detail": "The target points back to the original capability on disk.",
        "sheet.sync.scope.project": "Project",
        "sheet.sync.scope.global": "Global",
        "sheet.sync.scope.project.detail": "Install into this project only.",
        "sheet.sync.scope.global.detail": "Install for local projects on this Mac.",
        "sheet.sync.scope.project.summary": "Installs into the project",
        "sheet.sync.scope.global.summary": "Installs globally",
        "sheet.sync.scope.project.summary.detail": "Only this project gets the synced capability.",
        "sheet.sync.scope.global.summary.detail": "The selected agent can use it across local projects.",
        "sheet.scoped.subtitle": "Review current capability",
        "sheet.scoped.header.linkeddelete": "Confirm Linked Delete",
        "sheet.scoped.impact.linkedremoved": "Linked targets will be removed",
        "sheet.scoped.impact.permanentdelete": "Permanent delete",
        "sheet.scoped.impact.willbedisabled": "Capability will be disabled",
        "sheet.scoped.action.continue": "Continue",
        "sheet.hide.title": "Hidden Categories",
        "sheet.hide.subtitle": "Second filter visibility",
        "sheet.hide.showall": "Show All",
        "sheet.action.save": "Save",
        "sheet.hide.row.alwaysvisible": "Always visible",
        "sheet.hide.row.hidden": "Hidden",
        "sheet.hide.row.visible": "Visible",
        "sheet.apply.title": "Confirm Changes",
        "sheet.apply.subtitle": "Nothing has been changed yet. Review the file operations before applying.",
        "sheet.apply.row.action": "Action",
        "sheet.apply.row.capability": "Capability",
        "sheet.apply.row.operations": "Operations",
        "sheet.apply.row.confirmation": "Confirmation",
        "sheet.apply.confirmation.required": "Required",
        "sheet.apply.confirmation.notrequired": "Not required",
        "sheet.apply.operation.target": "Target: %@",
        "sheet.action.apply": "Apply",
        "sidebar.collapse": "Collapse sidebar",
        "sidebar.section.environment": "Environment",
        "sidebar.thismac.title": "This Mac",
        "sidebar.thismac.subtitle": "User and device scope",
        "sidebar.section.projects": "Projects",
        "sidebar.openProject": "Open project",
        "sidebar.openProject.row.title": "Open Project...",
        "sidebar.openProject.row.subtitle": "Choose a repository",
        "sidebar.dragToReorder": "Drag to reorder",
        "sidebar.settings.subtitle": "Preferences",
        "sidebar.menu.pinToTop": "Pin to Top",
        "sidebar.menu.delete": "Delete",
        "sidebar.expand": "Expand sidebar",
        "collection.section.expand": "Expand %@",
        "collection.section.collapse": "Collapse %@",
        "collection.shelf.items": "%d items",
        "collection.type.plugins": "Plugins",
        "collection.type.skills": "Skills",
        "collection.type.agents": "Agents",
        "collection.type.commands": "Commands",
        "collection.type.hooks": "Hooks",
        "collection.type.instructions": "Instructions",
        "collection.type.other": "Other",
        "collection.kind.plugin": "Plugin",
        "collection.kind.group": "Group",
        "collection.mirror.linked": "Linked mirrors",
        "collection.mirror.copied": "Same hash copies",
        "collection.mirror.sameSource": "Same source",
        "collection.protocol.skill": "Skill capability",
        "collection.protocol.agent": "Subagent",
        "collection.protocol.plugin": "Plugin package",
        "collection.protocol.mcp": "MCP server",
        "collection.protocol.command": "Command",
        "collection.protocol.instruction": "Instruction",
        "collection.protocol.capability": "Capability",
        "collection.badge.items": "%@ items",
        "collection.sync.help": "Sync to another agent",
        "collection.visible.to": "Visible to %@",
        "collection.visible.toSync": "%@. Sync to another agent",
        "collection.sync.accessibility": "Sync capability to another agent",
        "onboarding.eyebrow.welcome": "WELCOME",
        "onboarding.eyebrow.scope": "SCOPE",
        "onboarding.eyebrow.agents": "AGENT TABS",
        "onboarding.eyebrow.organize": "ORGANIZE",
        "onboarding.eyebrow.actions": "CORE ACTIONS",
        "onboarding.eyebrow.ready": "READY",
        "onboarding.title.welcome": "One console for\nevery agent.",
        "onboarding.title.scope": "This Mac,\nand this project.",
        "onboarding.title.agents": "Every tab is\na point of view.",
        "onboarding.title.organize": "Filter, sort,\nsee the state.",
        "onboarding.title.actions": "Hide. Copy.\nRemove.",
        "onboarding.title.ready": "You're all set.",
        "onboarding.body.welcome": "Orbita is your **single console** for coding-agent capabilities — Skills, Plugins, Commands, Hooks, MCP, Rules, Instructions — across **Codex**, **Claude Code**, **Trae** and the shared `.agents` workspace.",
        "onboarding.body.scope": "Capabilities live in **two places**: your whole Mac (`~/.codex`, `~/.claude`) and the project you open. Orbita shows **both at once**, so you always know what an agent really sees here.",
        "onboarding.body.agents": "Each tab is **one agent's view**. Switching tabs **never changes files** — it only re-filters the same scan, so you can compare what Codex, Claude Code and Trae each load.",
        "onboarding.body.organize": "Filter by type, sort by name or date, and read each section by **effective status** — Enabled, Disabled, Discovered. Grouping keeps a plugin's children together.",
        "onboarding.body.actions": "Three actions, three meanings. **Tap a card** to see what each one does — one hides, one copies, one removes.",
        "onboarding.body.ready": "Open a project from the sidebar to begin. You can **replay this guide** any time from **Settings → Guide**.",
        "onboarding.progress.step": "Step %d of %d",
        "onboarding.button.skip": "Skip",
        "onboarding.button.back": "Back",
        "onboarding.button.getStarted": "Get started",
        "onboarding.button.next": "Next",
        "onboarding.language.chinese": "Chinese",
        "onboarding.language.help": "Language",
        "onboarding.illustration.welcome": "A row of capability types",
        "onboarding.scope.thisMac": "This Mac",
        "onboarding.scope.project": "Project",
        "onboarding.illustration.scope": "Project scope nested inside this Mac",
        "onboarding.illustration.agents": "Four agent tabs filtering the same capabilities",
        "onboarding.organize.filter.all": "All",
        "onboarding.organize.section.enabled": "Enabled",
        "onboarding.organize.section.disabled": "Disabled",
        "onboarding.illustration.organize": "Capabilities filtered, sorted and grouped by status",
        "onboarding.action.disable.title": "Disable",
        "onboarding.action.disable.detail": "Hide it here. The source is cached and fully reversible.",
        "onboarding.action.fork.detail": "Copy it into another agent's own folder.",
        "onboarding.action.delete.title": "Delete",
        "onboarding.action.delete.detail": "Remove the capability for good.",
        "onboarding.illustration.actions": "Disable hides, Fork copies, Delete removes",
        "onboarding.ready.openProject": "Open a project to begin",
        "onboarding.illustration.ready": "Setup complete",
        "permission.denied.noProbes": "Orbita could not verify access to protected macOS folders. If you just enabled Full Disk Access, quit and reopen Orbita.",
        "permission.denied.notYet": "Orbita cannot verify Full Disk Access yet. Grant Full Disk Access, then quit and reopen Orbita.",
        "permission.title": "Orbita needs Full Disk Access",
        "permission.subtitle.reads": "Orbita reads local coding-agent directories such as ~/.agents, ~/.codex, ~/.claude, project workspaces, package caches, and lock files. Enable Full Disk Access before using the app.",
        "permission.subtitle.skip": "If you skip, Orbita will preflight the exact user and project paths it is about to scan so macOS can show permission prompts before the workspace opens.",
        "permission.step1.title": "Open Privacy & Security",
        "permission.step1.detail": "Click the button below to open System Settings.",
        "permission.step2.title": "Enable Orbita",
        "permission.step2.detail": "Go to Full Disk Access and turn Orbita on. If Orbita is not listed, add the app manually.",
        "permission.step3.title": "Quit and reopen Orbita",
        "permission.step3.detail": "macOS applies this permission to the next app launch.",
        "permission.button.openSettings": "Open System Settings",
        "permission.button.checking": "Checking Access",
        "permission.button.skip": "Skip and Continue",
        "permission.button.quit": "Quit Orbita",
        "app.access.stillCannotRead": "Orbita still cannot read %@. Allow the macOS prompt, then try again or enable Full Disk Access.",
        "app.access.requiredFolder": "a required folder",
        "app.error.deleteCommandFailed": "Delete command failed: %@",
        "apply.success.clean": "Workspace cleaned.",
        "apply.success.delete": "Deleted %@ item(s).",
        "apply.success.disable": "Disabled %@ item(s).",
        "apply.success.enable": "Enabled %@ item(s).",
        "apply.success.merge": "Workspace merged.",
        "apply.success.rollback": "Rolled back.",
        "app.section.itemCount": "%d items",
        "app.section.enabled": "Enabled",
        "app.section.disabled": "Disabled",
        "app.subsection.other": "Other",
        "app.confirm.deleteTitle": "Delete %@?",
        "app.confirm.disableTitle": "Disable %@?",
        "app.confirm.deleteCurrent": "Delete Current",
        "app.confirm.disableCurrent": "Disable Current",
        "app.confirm.alsoDeleteSymlinks": "This will also delete linked symlinks for %@. Confirm delete?",
        "app.confirm.deleteSourceWithSymlinks": "This will permanently delete the current capability source%@. %@ are symlinks to this source and will be deleted together to avoid broken links.",
        "app.confirm.deleteSelectionGrouped": "This will permanently delete the current selection%@, including %d grouped capability sources.",
        "app.confirm.deleteSource": "This will permanently delete the current capability source%@.",
        "app.confirm.disableSelectionGrouped": "This will disable the current selection%@, including %d grouped capability sources.",
        "app.confirm.disableSource": "This will disable the current capability source%@.",
        "app.confirm.disableCacheAndSymlink": "%@ Symbolic links are removed as links only. Because this host has no native disable, real files are moved into Orbita's disabled store (scope-correct: a project source under .orbita/disabled, a user source under ~/.orbita/disabled) and moved back when enabled.",
        "app.confirm.disableCache": "%@ Because this host has no native disable, the real file is moved into Orbita's disabled store (scope-correct: a project source under .orbita/disabled, a user source under ~/.orbita/disabled) and moved back when enabled.",
        "app.confirm.disableSymlinkOnly": "%@ Symbolic links are removed as links only; their targets remain untouched.",
        "app.confirm.disableIntent": "%@ Orbita will record disabled intent in .agents.",
        "app.confirm.forAgentSuffix": " for %@",
        // Settings — chrome
        "settings.title": "Settings",
        "settings.close": "Close settings",
        "settings.page.general": "General",
        "settings.page.plugins": "Plugins",
        "settings.page.release": "Release",

        // Settings — General
        "settings.general.subtitle": "Scan behavior, language, and capability display preferences.",
        "settings.general.preferences": "Preferences",
        "settings.general.refresh.title": "Refresh",
        "settings.general.refresh.subtitle": "Controls cache lifetime before Orbita scans capabilities again.",
        "settings.general.sort.title": "Capability sort",
        "settings.general.sort.subtitle": "Default order for capability lists and grouped sections.",
        "settings.general.language.title": "Language",
        "settings.general.language.subtitle": "Display language used by the Orbita interface.",
        "settings.general.language.picker": "Display language",

        // Settings — Plugins
        "settings.plugins.subtitle": "Maintenance commands for Codex, Claude Code, and .agents skills.",
        "settings.plugins.maintenance": "Maintenance",
        "settings.plugins.codex.title": "Codex marketplaces",
        "settings.plugins.codex.detail": "Refresh configured Git marketplace snapshots and rescan Orbita.",
        "settings.plugins.claude.title": "Claude Code plugins",
        "settings.plugins.claude.detail": "List installed plugins with enable status. Update individual plugins from the inspector.",
        "settings.plugins.agents.title": ".agents skills",
        "settings.plugins.agents.detail": "Trigger Skills CLI update in the current project context.",

        // Settings — Release
        "settings.release.subtitle": "Version metadata, signed DMG release, notarization, and Sparkle readiness.",
        "settings.release.pipeline": "Pipeline",
        "settings.release.group.build": "Build and CI",
        "settings.release.group.trust": "Signing and Notarization",
        "settings.release.group.update": "Auto-Update",
        "settings.release.actions": "Actions",
        "settings.release.action.gh.title": "Check GitHub CLI",
        "settings.release.action.gh.detail": "Verify local gh authentication before creating tags or releases.",
        "settings.release.action.tag.title": "Tag current version",
        "settings.release.action.tag.detail": "Create a local DMG, push the release tag, then let GitHub Actions sign, notarize, staple, and publish the DMG.",
        "settings.release.row.workflow": "Workflow",
        "settings.release.row.tag": "Tag",
        "settings.release.row.artifact": "Artifact",
        "settings.release.row.signing": "Signing",
        "settings.release.row.runtime": "Runtime",
        "settings.release.row.notary": "Notary",
        "settings.release.row.updater": "Updater",
        "settings.release.row.feed": "Feed",
        "settings.release.row.security": "Security",
        "settings.release.row.bundle": "Bundle",
        "settings.release.row.project": "Project",
        "settings.release.row.path": "Path",

        "settings.command.output": "Command Output",
        "settings.command.failed": "Command Failed",
        "settings.command.empty": "(no output)",
        "settings.command.run": "Run",
        "settings.command.running": "Running",

        // Refresh policy
        "refresh.thirtyMinutes": "30 minutes",
        "refresh.oneHour": "1 hour",
        "refresh.automatic": "Automatic",
        "refresh.manual": "Manual",
        "refresh.explain.thirtyMinutes": "Re-scans whenever the cached results are more than 30 minutes old.",
        "refresh.explain.oneHour": "Re-scans whenever the cached results are more than 1 hour old.",
        "refresh.explain.automatic": "Orbita decides for you: a project re-scans after about 30 minutes, This Mac after about 1 hour.",
        "refresh.explain.manual": "Never re-scans on its own — only when you click Refresh.",

        // Sort
        "sort.name": "Name",
        "sort.modifiedNewest": "Modified newest",
        "sort.modifiedOldest": "Modified oldest",
        "sort.statusPriority": "Status (issues first)",
        "sort.riskLevel": "Risk (highest first)",

        // Capability tiles
        "group.prefix.subtitle": "Grouped by the %@-* prefix",
        "hook.timing": "Hook timing",
        "hook.timing.format": "%@ hook timing",

        // Onboarding guide
        "settings.page.guide": "Guide",
        "settings.guide.subtitle": "The quick-start walkthrough and when it appears.",
        "settings.guide.card": "Quick start",
        "settings.guide.replay.title": "Replay guide",
        "settings.guide.replay.subtitle": "Reopen the illustrated walkthrough of scopes, agent tabs, and core actions.",
        "settings.guide.replay.button": "Show guide",
        "settings.guide.frequency.title": "Show on launch",
        "settings.guide.frequency.subtitle": "First launch only is normal. “Every launch” and “Never” are debug conveniences for re-checking the guide without reinstalling.",
        "settings.guide.frequency.firstLaunch": "First launch",
        "settings.guide.frequency.always": "Every launch",
        "settings.guide.frequency.never": "Never",

        // Toast
        "toast.comingSoon": "Coming soon"
    ]

    static let simplifiedChinese: [String: String] = [
        "onboarding.action.fork.title": "复制",

        // === i18n second pass (enum/display/store leftovers) ===
        "risk.info": "仅元数据",
        "risk.read": "读取文件",
        "risk.write": "写入文件",
        "risk.exec": "执行命令",
        "risk.network": "网络访问",
        "risk.secret": "密钥/环境变量",
        "risk.global": "全局范围",
        "applyAction.merge": "合并到 .agents",
        "applyAction.rollback": "回滚",
        "applyAction.clean": "清理",
        "op.readSource": "读取源",
        "op.createDirectory": "创建文件夹",
        "op.createSymlink": "创建链接",
        "op.copyPath": "复制路径",
        "op.cachePath": "缓存源",
        "op.restorePath": "恢复源",
        "op.removePath": "移除路径",
        "op.writeFile": "写入文件",
        "op.appendLog": "追加日志",
        "category.all": "全部",
        "category.plugins": "插件",
        "category.skills": "技能",
        "category.agents": "Agent",
        "category.commands": "命令",
        "category.mcp": "MCP",
        "category.hooks": "钩子",
        "category.instructions": "指令说明",
        "sort.modified": "修改时间",
        "status.enabled": "已启用",
        "status.disabled": "已停用",
        "status.broken": "已损坏",
        "status.needsAttention": "需要关注",
        "status.reviewNeeded": "需要复查",
        "status.duplicate": "重复",
        "type.plugin": "插件",
        "type.skill": "技能",
        "type.agent": "Agent",
        "type.mcp": "MCP",
        "type.rule": "规范",
        "type.instruction": "指令说明",
        "type.hook": "Hook",
        "type.command": "命令",
        "type.unknown": "未知",
        "source.packages.lower": "软件包",
        "source.project.lower": "项目",
        "source.packages": "软件包",
        "source.project": "项目",
        "source.other": "其他",
        "scope.thisMac": "这台 Mac",
        "scope.openProject": "打开项目",
        "scan.neverRefreshed": "从未刷新",
        "scan.lastRefresh": "上次刷新 %@",
        "scan.usingCachedSnapshot": "使用缓存快照",
        "scan.refreshingCachedSnapshot": "正在刷新缓存快照",
        "scan.foundCapabilities": "找到 %d 项能力",
        "scan.preparing": "正在准备 %@",
        "scan.checkingInstructions": "正在检查项目说明",
        "scan.checkingCodex": "正在检查 Codex",
        "scan.checkingClaude": "正在检查 Claude Code",
        "scan.checkingRules": "正在检查项目规范",
        "scan.checkingMCP": "正在检查 MCP",
        "scan.checkingAgents": "正在检查 .agents",
        "scan.scanningSkills": "正在扫描 Skills",
        "scan.scannedSkillsCount": "已扫描 Skills - 找到 %d 项",
        "scan.scannedSkills": "已扫描 Skills",
        "scan.finishing": "正在完成扫描",
        "apply.failure.failedAt": "失败于：%@。",
        "apply.failure.alreadyApplied": "%d 项操作已应用。",
        "apply.failure.notAttempted": "%d 项操作未尝试。",
        "app.menu.checkForUpdates": "检查更新…",
        "onboarding.tile.skill": "技能",
        "onboarding.tile.rule": "规范",
        "main.markdownPreview.back": "返回",
        "markdown.preview.engine": "Markdown",
        "settings.release.buildFor": "为 %2$@ 构建 %1$@",

        // === i18n full-coverage (home-side views) — auto-generated ===
        "main.loading.scanning": "正在扫描 %@",
        "main.error.unableToScan": "无法扫描",
        "main.summary.total": "总计",
        "main.summary.plugins": "插件",
        "main.summary.skills": "技能",
        "main.summary.agents": "Agent",
        "main.summary.commands": "命令",
        "main.summary.hooks": "钩子",
        "main.loading.percent": "%d%%",
        "main.refresh.refreshing": "正在刷新…",
        "main.macScope.show": "显示这台 Mac",
        "main.macScope.hide": "隐藏这台 Mac",
        "main.macScope.show.help": "显示来自这台 Mac 的能力",
        "main.macScope.hide.help": "隐藏来自这台 Mac 的能力",
        "main.filter.addAgent": "添加 Coding Agent",
        "main.filter.overview": "概览",
        "main.menu.pinToTop": "置顶",
        "main.menu.delete": "删除",
        "main.filter.hideCategories": "隐藏分类",
        "main.menu.hide": "隐藏",
        "main.chip.dragToReorder": "拖动以重新排序",
        "main.empty.noCapabilities": "暂无能力",
        "main.empty.noSearchResults": "没有匹配“%@”的能力",
        "main.empty.noFilterResults": "没有符合所选标记的能力",
        "main.search.placeholder": "搜索能力",
        "main.search.clear": "清除搜索",
        "main.summary.risky": "风险",
        "main.filter.flags.help": "仅显示带所选标记的能力",
        "main.filter.clearFlags": "清除",
        "main.flag.broken": "损坏",
        "main.flag.drifted": "漂移",
        "main.flag.shadowed": "被遮蔽",
        "main.flag.risky": "有风险",
        "main.flag.disabled": "已禁用",
        "bulk.groupName": "已选 %@ 项",
        "bulk.selected": "已选 %@ 项",
        "bulk.enable": "启用",
        "bulk.disable": "禁用",
        "bulk.delete": "删除",
        "bulk.clear": "清除选择",
        "bulk.hint": "按住 ⌘ 或 ⇧ 点击磁贴可多选",
        "main.empty.openProject.title": "打开项目",
        "main.empty.openProject.subtitle": "选择一个仓库以查看本地 Coding Agent 能力。",
        "main.empty.openProject.button": "打开项目…",
        "inspector.field.scope": "作用域",
        "inspector.field.status": "状态",
        "inspector.field.version": "版本",
        "inspector.field.access": "权限",
        "inspector.field.source": "来源",
        "inspector.field.canon": "规范路径",
        "inspector.field.agents": "Agent",
        "inspector.field.lock": "锁",
        "inspector.field.ref": "引用",
        "inspector.field.skill": "技能",
        "inspector.field.hash": "哈希",
        "inspector.field.children": "子项",
        "inspector.delete.cancel": "取消",
        "inspector.action.delete": "删除",
        "inspector.delete.title": "删除 %@？",
        "inspector.delete.subtitle": "原生插件操作",
        "inspector.delete.permanent.title": "永久删除",
        "inspector.delete.permanent.detail": "这将通过该能力的原生生命周期命令将其移除。列表会立即更新；若命令失败，Orbita 会恢复到之前的状态。",
        "inspector.command.label": "命令",
        "inspector.empty.title": "未选择",
        "inspector.empty.subtitle": "选择一项能力以查看其来源、作用域、权限和加载路径。",
        "inspector.action.running": "运行中",
        "inspector.action.enable": "启用",
        "inspector.action.disable": "停用",
        "inspector.action.hide": "隐藏检视器",
        "inspector.native.managerFallback": "插件",
        "inspector.native.newVersion": "有可用新版本 %@",
        "inspector.section.skillsCLI": "Skills CLI",
        "inspector.section.nativePlugin": "原生插件",
        "inspector.version.current": "当前",
        "inspector.version.unknown": "未知",
        "inspector.version.latest": "最新",
        "inspector.result.failed.title": "%@ 失败",
        "inspector.result.failed.detail": "命令在返回可读的插件详情前已失败。",
        "inspector.result.installed.title": "已安装",
        "inspector.result.installed.detail": "%@ 已从其 Skills CLI 锁定来源安装。",
        "inspector.result.enabled.title": "已启用",
        "inspector.result.enabled.detail": "%@ 已启用。如果宿主应用未立即生效，请重启它。",
        "inspector.result.disabled.title": "已停用",
        "inspector.result.disabled.detail": "%@ 已停用。如果宿主应用未立即生效，请重启它。",
        "inspector.result.deleted.title": "已删除",
        "inspector.result.deleted.detail": "%@ 已删除。如果宿主应用未立即生效，请重启它。",
        "inspector.result.updateAvailable.title": "有可用更新",
        "inspector.result.updateAvailable.detail": "%@ 可从 %@ 升级到 %@。点击“更新”以应用。",
        "inspector.result.checked.title": "已检查",
        "inspector.result.canMove.detail": "%@ 可从 %@ 升级到 %@。",
        "inspector.result.isChecked.detail": "%@ 已检查。",
        "inspector.version.unknown.lower": "未知",
        "inspector.result.checked.noVersion": "插件命令已完成，但未返回该插件的版本信息。",
        "inspector.result.updated.title": "已更新",
        "inspector.result.updated.detail": "%@ 已从 %@ 升级到 %@。如果宿主应用未立即采用新版本，请重启它。",
        "inspector.result.upToDate.title": "已是最新版本",
        "inspector.result.upToDate.detail": "%@ 已是当前可用的最新版本。",
        "inspector.result.updateCompleted.title": "更新已完成",
        "inspector.result.updateCompleted.detail": "%@ 已更新。如果宿主应用未立即生效，请重启它。",
        "inspector.action.reinstall": "重新安装",
        "inspector.action.update": "更新",
        "inspector.dot.broken": "已损坏",
        "inspector.dot.needsAttention": "需要关注",
        "inspector.dot.reviewNeeded": "需要复查",
        "inspector.dot.ready": "就绪",
        "inspector.reason.broken.title": "来源已损坏",
        "inspector.reason.broken.detail": "Orbita 找到了该能力的记录，但其来源路径缺失、不可读或无法解析。",
        "inspector.reason.shadowed.title": "被更高优先级的作用域覆盖",
        "inspector.reason.shadowed.detail": "在更高优先级的作用域中存在同类型同名的另一项能力。优先级顺序为：项目、用户、已安装、环境。",
        "inspector.reason.drift.title": "检测到漂移",
        "inspector.reason.risky.title": "权限需要复查",
        "inspector.reason.risky.detail": "该能力请求 %@。",
        "inspector.reason.disabled.title": "已停用",
        "inspector.reason.disabledCodex.title": "已对 Codex 停用",
        "inspector.reason.duplicate.title": "名称重复",
        "inspector.reason.ready.title": "就绪",
        "inspector.reason.ready.detail": "Orbita 找到了该能力，且未检测到断链、漂移、覆盖或需复查的标记。",
        "inspector.drift.detail": "同类型同名的能力存在于多个位置，且内容哈希不同。",
        "inspector.drift.guidance": "选定一个位置作为唯一来源，其余改为符号链接或删除，确保各 Agent 加载同一版本。",
        "inspector.drift.guidance.title": "如何收敛",
        "inspector.drift.location.current": "当前查看",
        "inspector.drift.location.differs": "内容不同",
        "inspector.drift.locations.intro": "这个能力存在于 %@ 个位置，且各处内容已不一致：",
        "inspector.drift.locations.title": "漂移发生在哪里",
        "inspector.drift.summary": "发现 %@ 处内容已不一致的副本。",
        "scope.environment": "环境",
        "scope.installed": "已安装",
        "scope.project": "项目",
        "scope.user": "用户",
        "inspector.duplicate.detail": "Orbita 找到了多个同类型同名的能力。",
        "inspector.disabled.byManager": "%@ 将该插件标记为已停用。",
        "inspector.disabled.byManifest": ".agents 清单将该能力标记为已停用。",
        "inspector.disabled.codexSkill": "Codex 配置在 %@ 中停用了此 SKILL.md 路径。其他 agent 仍可能加载同一文件。",
        "inspector.field.value.placeholder": "-",
        "inspector.markdown.title": "Markdown 预览",
        "inspector.markdown.preview": "预览",
        "inspector.markdown.openFull": "打开完整 Markdown 预览",
        "inspector.markdown.loading": "正在加载预览",
        "inspector.markdown.unavailable": "没有可用的 Markdown 预览。",
        "inspector.source.openFolder": "打开来源文件夹",
        "inspector.markdown.readError": "无法读取 Markdown：%@",
        "inspector.markdown.truncated": "预览已截断。",
        "sheet.addagent.field.source": "Agent 来源",
        "sheet.addagent.field.displayname": "显示名称",
        "sheet.action.cancel": "取消",
        "sheet.action.add": "添加",
        "sheet.addagent.preset.custom": "自定义",
        "sheet.addagent.field.name.placeholder": "Agent 名称",
        "sheet.addagent.field.capabilitymodel": "能力模型",
        "sheet.addagent.preset.manualview": "手动能力视图",
        "sheet.addagent.noglobalpath": "无全局路径",
        "sheet.addagent.header.title": "添加 Coding Agent",
        "sheet.addagent.header.subtitle": "预设或自定义能力视图",
        "sheet.addagent.scheme.generic": "通用",
        "sheet.addagent.scheme.default": "默认",
        "sheet.addagent.scheme.note": "你的自定义工具使用默认方案——会显示所有已启用的能力。Agent 专属方案（Codex/Claude 可见性规则）尚未在此配置。",
        "sheet.addagent.skillspaths.title": "Skills CLI 安装路径",
        "sheet.addagent.skillspaths.shared": "共享",
        "sheet.addagent.skillspaths.dedicated": "专用",
        "sheet.sync.title": "同步到 Agent",
        "sheet.action.sync": "同步",
        "sheet.sync.step.destination": "目标",
        "sheet.sync.destination.syncto": "同步到 %@",
        "sheet.sync.destination.choose": "选择一个 Agent",
        "sheet.sync.step.method": "方式",
        "sheet.sync.method.copy": "复制",
        "sheet.sync.method.copy.detail": "在目标位置创建一个独立的文件。",
        "sheet.sync.method.symlink": "符号链接",
        "sheet.sync.method.symlink.detail": "让目标指回此源文件。",
        "sheet.sync.step.location": "位置",
        "sheet.sync.preview.agent": "Agent",
        "sheet.sync.status.choose": "选择一个目标 Agent。",
        "sheet.sync.status.alreadyhas": "%@ 已拥有此能力。",
        "sheet.sync.status.ready": "已准备好同步到 %@。",
        "sheet.sync.row.alreadyavailable": "已可用",
        "sheet.sync.row.availabletarget": "可用目标",
        "sheet.sync.summary.copy.title": "副本相互独立",
        "sheet.sync.summary.symlink.title": "符号链接跟随源文件",
        "sheet.sync.summary.copy.detail": "之后对原文件的修改不会自动更新此目标。",
        "sheet.sync.summary.symlink.detail": "目标指回磁盘上的原始能力。",
        "sheet.sync.scope.project": "项目",
        "sheet.sync.scope.global": "全局",
        "sheet.sync.scope.project.detail": "仅安装到此项目。",
        "sheet.sync.scope.global.detail": "为这台 Mac 上的本地项目安装。",
        "sheet.sync.scope.project.summary": "安装到此项目",
        "sheet.sync.scope.global.summary": "全局安装",
        "sheet.sync.scope.project.summary.detail": "只有此项目会获得同步的能力。",
        "sheet.sync.scope.global.summary.detail": "所选 Agent 可在各本地项目中使用它。",
        "sheet.scoped.subtitle": "查看当前能力",
        "sheet.scoped.header.linkeddelete": "确认关联删除",
        "sheet.scoped.impact.linkedremoved": "关联目标将被移除",
        "sheet.scoped.impact.permanentdelete": "永久删除",
        "sheet.scoped.impact.willbedisabled": "能力将被停用",
        "sheet.scoped.action.continue": "继续",
        "sheet.hide.title": "隐藏的分类",
        "sheet.hide.subtitle": "二级筛选器可见性",
        "sheet.hide.showall": "全部显示",
        "sheet.action.save": "保存",
        "sheet.hide.row.alwaysvisible": "始终可见",
        "sheet.hide.row.hidden": "已隐藏",
        "sheet.hide.row.visible": "可见",
        "sheet.apply.title": "确认更改",
        "sheet.apply.subtitle": "尚未做任何更改。请在应用前查看文件操作。",
        "sheet.apply.row.action": "操作",
        "sheet.apply.row.capability": "能力",
        "sheet.apply.row.operations": "操作数",
        "sheet.apply.row.confirmation": "确认",
        "sheet.apply.confirmation.required": "需要",
        "sheet.apply.confirmation.notrequired": "不需要",
        "sheet.apply.operation.target": "目标：%@",
        "sheet.action.apply": "应用",
        "sidebar.collapse": "收起边栏",
        "sidebar.section.environment": "环境",
        "sidebar.thismac.title": "这台 Mac",
        "sidebar.thismac.subtitle": "用户与设备作用域",
        "sidebar.section.projects": "项目",
        "sidebar.openProject": "打开项目",
        "sidebar.openProject.row.title": "打开项目...",
        "sidebar.openProject.row.subtitle": "选择一个仓库",
        "sidebar.dragToReorder": "拖动以重新排序",
        "sidebar.settings.subtitle": "偏好设置",
        "sidebar.menu.pinToTop": "置顶",
        "sidebar.menu.delete": "删除",
        "sidebar.expand": "展开边栏",
        "collection.section.expand": "展开 %@",
        "collection.section.collapse": "收起 %@",
        "collection.shelf.items": "%d 项",
        "collection.type.plugins": "插件",
        "collection.type.skills": "技能",
        "collection.type.agents": "Agent",
        "collection.type.commands": "命令",
        "collection.type.hooks": "Hook",
        "collection.type.instructions": "指令说明",
        "collection.type.other": "其他",
        "collection.kind.plugin": "插件",
        "collection.kind.group": "分组",
        "collection.mirror.linked": "链接镜像",
        "collection.mirror.copied": "相同哈希副本",
        "collection.mirror.sameSource": "相同来源",
        "collection.protocol.skill": "技能能力",
        "collection.protocol.agent": "子 Agent",
        "collection.protocol.plugin": "插件包",
        "collection.protocol.mcp": "MCP 服务器",
        "collection.protocol.command": "命令",
        "collection.protocol.instruction": "指令说明",
        "collection.protocol.capability": "能力",
        "collection.badge.items": "%@ 项",
        "collection.sync.help": "同步到另一个 Agent",
        "collection.visible.to": "对 %@ 可见",
        "collection.visible.toSync": "%@。同步到另一个 Agent",
        "collection.sync.accessibility": "将能力同步到另一个 Agent",
        "onboarding.eyebrow.welcome": "欢迎",
        "onboarding.eyebrow.scope": "作用域",
        "onboarding.eyebrow.agents": "AGENT 标签页",
        "onboarding.eyebrow.organize": "整理",
        "onboarding.eyebrow.actions": "核心操作",
        "onboarding.eyebrow.ready": "就绪",
        "onboarding.title.welcome": "一个控制台，\n统管所有 Agent。",
        "onboarding.title.scope": "本机，\n与当前项目。",
        "onboarding.title.agents": "每个标签页\n都是一种视角。",
        "onboarding.title.organize": "筛选、排序，\n看清状态。",
        "onboarding.title.actions": "隐藏。复制。\n移除。",
        "onboarding.title.ready": "一切就绪。",
        "onboarding.body.welcome": "Orbita 是管理 Coding Agent 能力的**统一控制台**——Skills、Plugins、Commands、Hooks、MCP、Rules、Instructions——覆盖 **Codex**、**Claude Code**、**Trae** 以及共享的 `.agents` 工作区。",
        "onboarding.body.scope": "能力存在于**两个位置**：整台 Mac（`~/.codex`、`~/.claude`）和你打开的项目。Orbita **同时展示两者**，让你随时清楚某个 Agent 在这里到底能看到什么。",
        "onboarding.body.agents": "每个标签页是**某个 Agent 的视角**。切换标签页**不会改动任何文件**——只是对同一次扫描重新过滤，方便你对比 Codex、Claude Code、Trae 各自加载了什么。",
        "onboarding.body.organize": "按类型筛选，按名称或日期排序，并按**生效状态**分区查看——已启用、已停用、已发现。分组会让插件的子能力保持在一起。",
        "onboarding.body.actions": "三个动作，三种含义。**点一下卡片**看看各自做什么——一个隐藏、一个复制、一个移除。",
        "onboarding.body.ready": "从侧边栏打开一个项目即可开始。你可以随时在**「设置 → 引导」**中**重看本引导**。",
        "onboarding.progress.step": "第 %d / %d 步",
        "onboarding.button.skip": "跳过",
        "onboarding.button.back": "上一步",
        "onboarding.button.getStarted": "开始使用",
        "onboarding.button.next": "下一步",
        "onboarding.language.chinese": "中文",
        "onboarding.language.help": "语言",
        "onboarding.illustration.welcome": "一排能力类型",
        "onboarding.scope.thisMac": "本机",
        "onboarding.scope.project": "项目",
        "onboarding.illustration.scope": "项目作用域嵌套在本机之中",
        "onboarding.illustration.agents": "四个 Agent 标签页过滤同一批能力",
        "onboarding.organize.filter.all": "全部",
        "onboarding.organize.section.enabled": "已启用",
        "onboarding.organize.section.disabled": "已停用",
        "onboarding.illustration.organize": "能力按状态筛选、排序与分组",
        "onboarding.action.disable.title": "停用",
        "onboarding.action.disable.detail": "在此隐藏。源被缓存，可完全恢复。",
        "onboarding.action.fork.detail": "复制到另一个 Agent 自己的目录。",
        "onboarding.action.delete.title": "删除",
        "onboarding.action.delete.detail": "彻底移除该能力。",
        "onboarding.illustration.actions": "停用即隐藏，Fork 即复制，删除即移除",
        "onboarding.ready.openProject": "打开一个项目即可开始",
        "onboarding.illustration.ready": "设置完成",
        "permission.denied.noProbes": "Orbita 无法验证对受保护的 macOS 文件夹的访问权限。如果你刚刚启用了“完全磁盘访问权限”，请退出并重新打开 Orbita。",
        "permission.denied.notYet": "Orbita 尚无法验证“完全磁盘访问权限”。请授予“完全磁盘访问权限”，然后退出并重新打开 Orbita。",
        "permission.title": "Orbita 需要“完全磁盘访问权限”",
        "permission.subtitle.reads": "Orbita 会读取本地 Coding Agent 目录，例如 ~/.agents、~/.codex、~/.claude，以及项目工作区、包缓存和锁文件。请在使用本应用前启用“完全磁盘访问权限”。",
        "permission.subtitle.skip": "如果你跳过，Orbita 会预检它即将扫描的确切用户路径和项目路径，以便 macOS 在工作区打开前弹出权限提示。",
        "permission.step1.title": "打开“隐私与安全性”",
        "permission.step1.detail": "点击下方按钮打开“系统设置”。",
        "permission.step2.title": "启用 Orbita",
        "permission.step2.detail": "进入“完全磁盘访问权限”并打开 Orbita 开关。如果列表中没有 Orbita，请手动添加该应用。",
        "permission.step3.title": "退出并重新打开 Orbita",
        "permission.step3.detail": "macOS 会在应用下次启动时应用此权限。",
        "permission.button.openSettings": "打开“系统设置”",
        "permission.button.checking": "正在检查访问权限",
        "permission.button.skip": "跳过并继续",
        "permission.button.quit": "退出 Orbita",
        "app.access.stillCannotRead": "Orbita 仍无法读取 %@。请允许 macOS 弹出的授权提示,然后重试,或开启“完全磁盘访问权限”。",
        "app.access.requiredFolder": "某个必需的文件夹",
        "app.error.deleteCommandFailed": "删除命令失败:%@",
        "apply.success.clean": "已清理工作区。",
        "apply.success.delete": "已删除 %@ 项。",
        "apply.success.disable": "已禁用 %@ 项。",
        "apply.success.enable": "已启用 %@ 项。",
        "apply.success.merge": "已合并工作区。",
        "apply.success.rollback": "已回滚。",
        "app.section.itemCount": "%d 项",
        "app.section.enabled": "已启用",
        "app.section.disabled": "已停用",
        "app.subsection.other": "其他",
        "app.confirm.deleteTitle": "删除 %@?",
        "app.confirm.disableTitle": "停用 %@?",
        "app.confirm.deleteCurrent": "删除当前项",
        "app.confirm.disableCurrent": "停用当前项",
        "app.confirm.alsoDeleteSymlinks": "这还会一并删除指向 %@ 的关联符号链接。确认删除?",
        "app.confirm.deleteSourceWithSymlinks": "这将永久删除当前能力源%@。%@ 是指向该源的符号链接,将一并删除以避免链接失效。",
        "app.confirm.deleteSelectionGrouped": "这将永久删除当前所选项%@,包括 %d 个分组内的能力源。",
        "app.confirm.deleteSource": "这将永久删除当前能力源%@。",
        "app.confirm.disableSelectionGrouped": "这将停用当前所选项%@,包括 %d 个分组内的能力源。",
        "app.confirm.disableSource": "这将停用当前能力源%@。",
        "app.confirm.disableCacheAndSymlink": "%@ 符号链接仅作为链接被移除。由于该宿主没有原生停用机制,真实文件会被移入 Orbita 的停用存储(作用域对应:项目源置于 .orbita/disabled,用户源置于 ~/.orbita/disabled),启用时再移回原处。",
        "app.confirm.disableCache": "%@ 由于该宿主没有原生停用机制,真实文件会被移入 Orbita 的停用存储(作用域对应:项目源置于 .orbita/disabled,用户源置于 ~/.orbita/disabled),启用时再移回原处。",
        "app.confirm.disableSymlinkOnly": "%@ 符号链接仅作为链接被移除;其指向的目标保持不变。",
        "app.confirm.disableIntent": "%@ Orbita 会在 .agents 中记录停用意图。",
        "app.confirm.forAgentSuffix": "(用于 %@)",
        "settings.title": "设置",
        "settings.close": "关闭设置",
        "settings.page.general": "通用",
        "settings.page.plugins": "插件",
        "settings.page.release": "发布",

        "settings.general.subtitle": "扫描行为、语言和能力展示偏好。",
        "settings.general.preferences": "偏好设置",
        "settings.general.refresh.title": "刷新",
        "settings.general.refresh.subtitle": "控制 Orbita 重新扫描能力前的缓存有效期。",
        "settings.general.sort.title": "能力排序",
        "settings.general.sort.subtitle": "能力列表和分组区块的默认排序。",
        "settings.general.language.title": "语言",
        "settings.general.language.subtitle": "Orbita 界面使用的显示语言。",
        "settings.general.language.picker": "显示语言",

        "settings.plugins.subtitle": "Codex、Claude Code 和 .agents 技能的维护命令。",
        "settings.plugins.maintenance": "维护",
        "settings.plugins.codex.title": "Codex 集市",
        "settings.plugins.codex.detail": "刷新已配置的 Git 集市快照,并重新扫描 Orbita。",
        "settings.plugins.claude.title": "Claude Code 插件",
        "settings.plugins.claude.detail": "列出已安装的插件及其启用状态。可在检视器中单独更新插件。",
        "settings.plugins.agents.title": ".agents 技能",
        "settings.plugins.agents.detail": "在当前项目上下文中触发 Skills CLI 更新。",

        "settings.release.subtitle": "版本元数据、签名 DMG 发布、公证以及 Sparkle 就绪状态。",
        "settings.release.pipeline": "流水线",
        "settings.release.group.build": "构建与 CI",
        "settings.release.group.trust": "签名与公证",
        "settings.release.group.update": "自动更新",
        "settings.release.actions": "操作",
        "settings.release.action.gh.title": "检查 GitHub CLI",
        "settings.release.action.gh.detail": "在创建标签或发布前,验证本地 gh 认证状态。",
        "settings.release.action.tag.title": "标记当前版本",
        "settings.release.action.tag.detail": "本地构建 DMG,推送发布标签,由 GitHub Actions 完成签名、公证、装订并发布 DMG。",
        "settings.release.row.workflow": "工作流",
        "settings.release.row.tag": "标签",
        "settings.release.row.artifact": "产物",
        "settings.release.row.signing": "签名",
        "settings.release.row.runtime": "运行时",
        "settings.release.row.notary": "公证",
        "settings.release.row.updater": "更新器",
        "settings.release.row.feed": "Feed",
        "settings.release.row.security": "安全",
        "settings.release.row.bundle": "Bundle",
        "settings.release.row.project": "项目",
        "settings.release.row.path": "路径",

        "settings.command.output": "命令输出",
        "settings.command.failed": "命令失败",
        "settings.command.empty": "(无输出)",
        "settings.command.run": "运行",
        "settings.command.running": "运行中",

        "refresh.thirtyMinutes": "30 分钟",
        "refresh.oneHour": "1 小时",
        "refresh.automatic": "自动",
        "refresh.manual": "手动",
        "refresh.explain.thirtyMinutes": "缓存结果超过 30 分钟后自动重新扫描。",
        "refresh.explain.oneHour": "缓存结果超过 1 小时后自动重新扫描。",
        "refresh.explain.automatic": "由 Orbita 自动决定：项目缓存约 30 分钟后、“这台 Mac”约 1 小时后重新扫描。",
        "refresh.explain.manual": "不会自动重新扫描，仅在你点击“刷新”时才扫描。",

        "sort.name": "名称",
        "sort.modifiedNewest": "最近修改优先",
        "sort.modifiedOldest": "最早修改优先",
        "sort.statusPriority": "状态（问题优先）",
        "sort.riskLevel": "风险（最高优先）",

        "group.prefix.subtitle": "前缀为 %@-* 聚合的内容",
        "hook.timing": "Hook 时机",
        "hook.timing.format": "Hook %@ 时机",

        "settings.page.guide": "引导",
        "settings.guide.subtitle": "快速上手引导，以及它的显示时机。",
        "settings.guide.card": "快速上手",
        "settings.guide.replay.title": "重看引导",
        "settings.guide.replay.subtitle": "重新观看关于作用域、Agent 标签页与核心操作的图文引导。",
        "settings.guide.replay.button": "显示引导",
        "settings.guide.frequency.title": "启动时显示",
        "settings.guide.frequency.subtitle": "“仅首次”为正常模式。“每次启动”和“从不”是调试用选项，方便无需重装即可反复查看引导。",
        "settings.guide.frequency.firstLaunch": "仅首次",
        "settings.guide.frequency.always": "每次启动",
        "settings.guide.frequency.never": "从不",

        "toast.comingSoon": "敬请期待"
    ]

    static let traditionalChinese: [String: String] = [
        "onboarding.action.fork.title": "複製",

        // === i18n second pass (enum/display/store leftovers) ===
        "risk.info": "僅中繼資料",
        "risk.read": "讀取檔案",
        "risk.write": "寫入檔案",
        "risk.exec": "執行命令",
        "risk.network": "網路存取",
        "risk.secret": "密鑰/環境變數",
        "risk.global": "全域範圍",
        "applyAction.merge": "合併到 .agents",
        "applyAction.rollback": "回滾",
        "applyAction.clean": "清理",
        "op.readSource": "讀取來源",
        "op.createDirectory": "建立資料夾",
        "op.createSymlink": "建立連結",
        "op.copyPath": "複製路徑",
        "op.cachePath": "快取來源",
        "op.restorePath": "還原來源",
        "op.removePath": "移除路徑",
        "op.writeFile": "寫入檔案",
        "op.appendLog": "附加日誌",
        "category.all": "全部",
        "category.plugins": "外掛",
        "category.skills": "技能",
        "category.agents": "Agent",
        "category.commands": "指令",
        "category.mcp": "MCP",
        "category.hooks": "掛鉤",
        "category.instructions": "指令說明",
        "sort.modified": "修改時間",
        "status.enabled": "已啟用",
        "status.disabled": "已停用",
        "status.broken": "已損壞",
        "status.needsAttention": "需要關注",
        "status.reviewNeeded": "需要複查",
        "status.duplicate": "重複",
        "type.plugin": "外掛",
        "type.skill": "技能",
        "type.agent": "Agent",
        "type.mcp": "MCP",
        "type.rule": "規範",
        "type.instruction": "指令說明",
        "type.hook": "Hook",
        "type.command": "指令",
        "type.unknown": "未知",
        "source.packages.lower": "套件",
        "source.project.lower": "專案",
        "source.packages": "套件",
        "source.project": "專案",
        "source.other": "其他",
        "scope.thisMac": "這台 Mac",
        "scope.openProject": "開啟專案",
        "scan.neverRefreshed": "從未重新整理",
        "scan.lastRefresh": "上次重新整理 %@",
        "scan.usingCachedSnapshot": "使用快取快照",
        "scan.refreshingCachedSnapshot": "正在重新整理快取快照",
        "scan.foundCapabilities": "找到 %d 項能力",
        "scan.preparing": "正在準備 %@",
        "scan.checkingInstructions": "正在檢查專案說明",
        "scan.checkingCodex": "正在檢查 Codex",
        "scan.checkingClaude": "正在檢查 Claude Code",
        "scan.checkingRules": "正在檢查專案規範",
        "scan.checkingMCP": "正在檢查 MCP",
        "scan.checkingAgents": "正在檢查 .agents",
        "scan.scanningSkills": "正在掃描 Skills",
        "scan.scannedSkillsCount": "已掃描 Skills - 找到 %d 項",
        "scan.scannedSkills": "已掃描 Skills",
        "scan.finishing": "正在完成掃描",
        "apply.failure.failedAt": "失敗於：%@。",
        "apply.failure.alreadyApplied": "%d 項操作已套用。",
        "apply.failure.notAttempted": "%d 項操作未嘗試。",
        "app.menu.checkForUpdates": "檢查更新…",
        "onboarding.tile.skill": "技能",
        "onboarding.tile.rule": "規範",
        "main.markdownPreview.back": "返回",
        "markdown.preview.engine": "Markdown",
        "settings.release.buildFor": "為 %2$@ 建置 %1$@",

        // === i18n full-coverage (home-side views) — auto-generated ===
        "main.loading.scanning": "正在掃描 %@",
        "main.error.unableToScan": "無法掃描",
        "main.summary.total": "總計",
        "main.summary.plugins": "外掛",
        "main.summary.skills": "技能",
        "main.summary.agents": "Agent",
        "main.summary.commands": "指令",
        "main.summary.hooks": "掛鉤",
        "main.loading.percent": "%d%%",
        "main.refresh.refreshing": "正在重新整理…",
        "main.macScope.show": "顯示這台 Mac",
        "main.macScope.hide": "隱藏這台 Mac",
        "main.macScope.show.help": "顯示來自這台 Mac 的能力",
        "main.macScope.hide.help": "隱藏來自這台 Mac 的能力",
        "main.filter.addAgent": "新增 Coding Agent",
        "main.filter.overview": "總覽",
        "main.menu.pinToTop": "置頂",
        "main.menu.delete": "刪除",
        "main.filter.hideCategories": "隱藏分類",
        "main.menu.hide": "隱藏",
        "main.chip.dragToReorder": "拖曳以重新排序",
        "main.empty.noCapabilities": "暫無能力",
        "main.empty.noSearchResults": "沒有符合“%@”的能力",
        "main.empty.noFilterResults": "沒有符合所選標記的能力",
        "main.search.placeholder": "搜尋能力",
        "main.search.clear": "清除搜尋",
        "main.summary.risky": "風險",
        "main.filter.flags.help": "僅顯示帶所選標記的能力",
        "main.filter.clearFlags": "清除",
        "main.flag.broken": "損壞",
        "main.flag.drifted": "漂移",
        "main.flag.shadowed": "被遮蔽",
        "main.flag.risky": "有風險",
        "main.flag.disabled": "已停用",
        "bulk.groupName": "已選 %@ 項",
        "bulk.selected": "已選 %@ 項",
        "bulk.enable": "啟用",
        "bulk.disable": "停用",
        "bulk.delete": "刪除",
        "bulk.clear": "清除選擇",
        "bulk.hint": "按住 ⌘ 或 ⇧ 點擊磁貼可多選",
        "main.empty.openProject.title": "開啟專案",
        "main.empty.openProject.subtitle": "選擇一個儲存庫以查看本機 Coding Agent 能力。",
        "main.empty.openProject.button": "開啟專案…",
        "inspector.field.scope": "作用域",
        "inspector.field.status": "狀態",
        "inspector.field.version": "版本",
        "inspector.field.access": "權限",
        "inspector.field.source": "來源",
        "inspector.field.canon": "規範路徑",
        "inspector.field.agents": "Agent",
        "inspector.field.lock": "鎖",
        "inspector.field.ref": "參照",
        "inspector.field.skill": "技能",
        "inspector.field.hash": "雜湊",
        "inspector.field.children": "子項",
        "inspector.delete.cancel": "取消",
        "inspector.action.delete": "刪除",
        "inspector.delete.title": "刪除 %@？",
        "inspector.delete.subtitle": "原生外掛操作",
        "inspector.delete.permanent.title": "永久刪除",
        "inspector.delete.permanent.detail": "這將透過該能力的原生生命週期指令將其移除。列表會立即更新；若指令失敗，Orbita 會還原到先前的狀態。",
        "inspector.command.label": "指令",
        "inspector.empty.title": "未選取",
        "inspector.empty.subtitle": "選取一項能力以查看其來源、作用域、權限和載入路徑。",
        "inspector.action.running": "執行中",
        "inspector.action.enable": "啟用",
        "inspector.action.disable": "停用",
        "inspector.action.hide": "隱藏檢視器",
        "inspector.native.managerFallback": "外掛",
        "inspector.native.newVersion": "有可用新版本 %@",
        "inspector.section.skillsCLI": "Skills CLI",
        "inspector.section.nativePlugin": "原生外掛",
        "inspector.version.current": "目前",
        "inspector.version.unknown": "未知",
        "inspector.version.latest": "最新",
        "inspector.result.failed.title": "%@ 失敗",
        "inspector.result.failed.detail": "指令在傳回可讀的外掛詳情前已失敗。",
        "inspector.result.installed.title": "已安裝",
        "inspector.result.installed.detail": "%@ 已從其 Skills CLI 鎖定來源安裝。",
        "inspector.result.enabled.title": "已啟用",
        "inspector.result.enabled.detail": "%@ 已啟用。如果宿主應用未立即生效，請重新啟動它。",
        "inspector.result.disabled.title": "已停用",
        "inspector.result.disabled.detail": "%@ 已停用。如果宿主應用未立即生效，請重新啟動它。",
        "inspector.result.deleted.title": "已刪除",
        "inspector.result.deleted.detail": "%@ 已刪除。如果宿主應用未立即生效，請重新啟動它。",
        "inspector.result.updateAvailable.title": "有可用更新",
        "inspector.result.updateAvailable.detail": "%@ 可從 %@ 升級到 %@。點擊「更新」以套用。",
        "inspector.result.checked.title": "已檢查",
        "inspector.result.canMove.detail": "%@ 可從 %@ 升級到 %@。",
        "inspector.result.isChecked.detail": "%@ 已檢查。",
        "inspector.version.unknown.lower": "未知",
        "inspector.result.checked.noVersion": "外掛指令已完成，但未傳回該外掛的版本資訊。",
        "inspector.result.updated.title": "已更新",
        "inspector.result.updated.detail": "%@ 已從 %@ 升級到 %@。如果宿主應用未立即採用新版本，請重新啟動它。",
        "inspector.result.upToDate.title": "已是最新版本",
        "inspector.result.upToDate.detail": "%@ 已是目前可用的最新版本。",
        "inspector.result.updateCompleted.title": "更新已完成",
        "inspector.result.updateCompleted.detail": "%@ 已更新。如果宿主應用未立即生效，請重新啟動它。",
        "inspector.action.reinstall": "重新安裝",
        "inspector.action.update": "更新",
        "inspector.dot.broken": "已損壞",
        "inspector.dot.needsAttention": "需要關注",
        "inspector.dot.reviewNeeded": "需要複查",
        "inspector.dot.ready": "就緒",
        "inspector.reason.broken.title": "來源已損壞",
        "inspector.reason.broken.detail": "Orbita 找到了該能力的記錄，但其來源路徑遺失、無法讀取或無法解析。",
        "inspector.reason.shadowed.title": "被更高優先級的作用域覆寫",
        "inspector.reason.shadowed.detail": "在更高優先級的作用域中存在同類型同名的另一項能力。優先級順序為：專案、使用者、已安裝、環境。",
        "inspector.reason.drift.title": "偵測到漂移",
        "inspector.reason.risky.title": "權限需要複查",
        "inspector.reason.risky.detail": "該能力請求 %@。",
        "inspector.reason.disabled.title": "已停用",
        "inspector.reason.disabledCodex.title": "已對 Codex 停用",
        "inspector.reason.duplicate.title": "名稱重複",
        "inspector.reason.ready.title": "就緒",
        "inspector.reason.ready.detail": "Orbita 找到了該能力，且未偵測到斷鏈、漂移、覆寫或需複查的標記。",
        "inspector.drift.detail": "同類型同名的能力存在於多個位置，且內容雜湊不同。",
        "inspector.drift.guidance": "選定一個位置作為唯一來源，其餘改為符號連結或刪除，確保各 Agent 載入同一版本。",
        "inspector.drift.guidance.title": "如何收斂",
        "inspector.drift.location.current": "目前檢視",
        "inspector.drift.location.differs": "內容不同",
        "inspector.drift.locations.intro": "這個能力存在於 %@ 個位置，且各處內容已不一致：",
        "inspector.drift.locations.title": "漂移發生在哪裡",
        "inspector.drift.summary": "發現 %@ 處內容已不一致的副本。",
        "scope.environment": "環境",
        "scope.installed": "已安裝",
        "scope.project": "專案",
        "scope.user": "使用者",
        "inspector.duplicate.detail": "Orbita 找到了多個同類型同名的能力。",
        "inspector.disabled.byManager": "%@ 將該外掛標記為已停用。",
        "inspector.disabled.byManifest": ".agents 資訊清单將該能力標記為已停用。",
        "inspector.disabled.codexSkill": "Codex 設定在 %@ 中停用了此 SKILL.md 路徑。其他 agent 仍可能載入同一檔案。",
        "inspector.field.value.placeholder": "-",
        "inspector.markdown.title": "Markdown 預覽",
        "inspector.markdown.preview": "預覽",
        "inspector.markdown.openFull": "開啟完整 Markdown 預覽",
        "inspector.markdown.loading": "正在載入預覽",
        "inspector.markdown.unavailable": "沒有可用的 Markdown 預覽。",
        "inspector.source.openFolder": "開啟來源資料夾",
        "inspector.markdown.readError": "無法讀取 Markdown：%@",
        "inspector.markdown.truncated": "預覽已截斷。",
        "sheet.addagent.field.source": "Agent 來源",
        "sheet.addagent.field.displayname": "顯示名稱",
        "sheet.action.cancel": "取消",
        "sheet.action.add": "新增",
        "sheet.addagent.preset.custom": "自訂",
        "sheet.addagent.field.name.placeholder": "Agent 名稱",
        "sheet.addagent.field.capabilitymodel": "能力模型",
        "sheet.addagent.preset.manualview": "手動能力檢視",
        "sheet.addagent.noglobalpath": "無全域路徑",
        "sheet.addagent.header.title": "新增 Coding Agent",
        "sheet.addagent.header.subtitle": "預設或自訂能力檢視",
        "sheet.addagent.scheme.generic": "通用",
        "sheet.addagent.scheme.default": "預設",
        "sheet.addagent.scheme.note": "你的自訂工具使用預設方案——會顯示所有已啟用的能力。Agent 專屬方案（Codex/Claude 可見性規則）尚未在此設定。",
        "sheet.addagent.skillspaths.title": "Skills CLI 安裝路徑",
        "sheet.addagent.skillspaths.shared": "共用",
        "sheet.addagent.skillspaths.dedicated": "專用",
        "sheet.sync.title": "同步到 Agent",
        "sheet.action.sync": "同步",
        "sheet.sync.step.destination": "目標",
        "sheet.sync.destination.syncto": "同步到 %@",
        "sheet.sync.destination.choose": "選擇一個 Agent",
        "sheet.sync.step.method": "方式",
        "sheet.sync.method.copy": "複製",
        "sheet.sync.method.copy.detail": "在目標位置建立一個獨立的檔案。",
        "sheet.sync.method.symlink": "符號連結",
        "sheet.sync.method.symlink.detail": "讓目標指回此來源檔案。",
        "sheet.sync.step.location": "位置",
        "sheet.sync.preview.agent": "Agent",
        "sheet.sync.status.choose": "選擇一個目標 Agent。",
        "sheet.sync.status.alreadyhas": "%@ 已擁有此能力。",
        "sheet.sync.status.ready": "已準備好同步到 %@。",
        "sheet.sync.row.alreadyavailable": "已可用",
        "sheet.sync.row.availabletarget": "可用目標",
        "sheet.sync.summary.copy.title": "副本相互獨立",
        "sheet.sync.summary.symlink.title": "符號連結跟隨來源檔案",
        "sheet.sync.summary.copy.detail": "之後對原檔案的修改不會自動更新此目標。",
        "sheet.sync.summary.symlink.detail": "目標指回磁碟上的原始能力。",
        "sheet.sync.scope.project": "專案",
        "sheet.sync.scope.global": "全域",
        "sheet.sync.scope.project.detail": "僅安裝到此專案。",
        "sheet.sync.scope.global.detail": "為這台 Mac 上的本機專案安裝。",
        "sheet.sync.scope.project.summary": "安裝到此專案",
        "sheet.sync.scope.global.summary": "全域安裝",
        "sheet.sync.scope.project.summary.detail": "只有此專案會取得同步的能力。",
        "sheet.sync.scope.global.summary.detail": "所選 Agent 可在各本機專案中使用它。",
        "sheet.scoped.subtitle": "查看目前能力",
        "sheet.scoped.header.linkeddelete": "確認關聯刪除",
        "sheet.scoped.impact.linkedremoved": "關聯目標將被移除",
        "sheet.scoped.impact.permanentdelete": "永久刪除",
        "sheet.scoped.impact.willbedisabled": "能力將被停用",
        "sheet.scoped.action.continue": "繼續",
        "sheet.hide.title": "隱藏的分類",
        "sheet.hide.subtitle": "次級篩選器可見性",
        "sheet.hide.showall": "全部顯示",
        "sheet.action.save": "儲存",
        "sheet.hide.row.alwaysvisible": "始終可見",
        "sheet.hide.row.hidden": "已隱藏",
        "sheet.hide.row.visible": "可見",
        "sheet.apply.title": "確認變更",
        "sheet.apply.subtitle": "尚未做任何變更。請在套用前查看檔案操作。",
        "sheet.apply.row.action": "操作",
        "sheet.apply.row.capability": "能力",
        "sheet.apply.row.operations": "操作數",
        "sheet.apply.row.confirmation": "確認",
        "sheet.apply.confirmation.required": "需要",
        "sheet.apply.confirmation.notrequired": "不需要",
        "sheet.apply.operation.target": "目標：%@",
        "sheet.action.apply": "套用",
        "sidebar.collapse": "收合側邊欄",
        "sidebar.section.environment": "環境",
        "sidebar.thismac.title": "這台 Mac",
        "sidebar.thismac.subtitle": "使用者與裝置作用域",
        "sidebar.section.projects": "專案",
        "sidebar.openProject": "開啟專案",
        "sidebar.openProject.row.title": "開啟專案...",
        "sidebar.openProject.row.subtitle": "選擇一個儲存庫",
        "sidebar.dragToReorder": "拖曳以重新排序",
        "sidebar.settings.subtitle": "偏好設定",
        "sidebar.menu.pinToTop": "置頂",
        "sidebar.menu.delete": "刪除",
        "sidebar.expand": "展開側邊欄",
        "collection.section.expand": "展開 %@",
        "collection.section.collapse": "收合 %@",
        "collection.shelf.items": "%d 項",
        "collection.type.plugins": "外掛",
        "collection.type.skills": "技能",
        "collection.type.agents": "Agent",
        "collection.type.commands": "指令",
        "collection.type.hooks": "Hook",
        "collection.type.instructions": "指令說明",
        "collection.type.other": "其他",
        "collection.kind.plugin": "外掛",
        "collection.kind.group": "群組",
        "collection.mirror.linked": "連結鏡像",
        "collection.mirror.copied": "相同雜湊副本",
        "collection.mirror.sameSource": "相同來源",
        "collection.protocol.skill": "技能能力",
        "collection.protocol.agent": "子 Agent",
        "collection.protocol.plugin": "外掛套件",
        "collection.protocol.mcp": "MCP 伺服器",
        "collection.protocol.command": "指令",
        "collection.protocol.instruction": "指令說明",
        "collection.protocol.capability": "能力",
        "collection.badge.items": "%@ 項",
        "collection.sync.help": "同步到另一個 Agent",
        "collection.visible.to": "對 %@ 可見",
        "collection.visible.toSync": "%@。同步到另一個 Agent",
        "collection.sync.accessibility": "將能力同步到另一個 Agent",
        "onboarding.eyebrow.welcome": "歡迎",
        "onboarding.eyebrow.scope": "作用域",
        "onboarding.eyebrow.agents": "AGENT 分頁",
        "onboarding.eyebrow.organize": "整理",
        "onboarding.eyebrow.actions": "核心操作",
        "onboarding.eyebrow.ready": "就緒",
        "onboarding.title.welcome": "一個主控台，\n統管所有 Agent。",
        "onboarding.title.scope": "本機，\n與目前專案。",
        "onboarding.title.agents": "每個分頁\n都是一種視角。",
        "onboarding.title.organize": "篩選、排序，\n看清狀態。",
        "onboarding.title.actions": "隱藏。複製。\n移除。",
        "onboarding.title.ready": "一切就緒。",
        "onboarding.body.welcome": "Orbita 是管理 Coding Agent 能力的**統一主控台**——Skills、Plugins、Commands、Hooks、MCP、Rules、Instructions——涵蓋 **Codex**、**Claude Code**、**Trae** 以及共享的 `.agents` 工作區。",
        "onboarding.body.scope": "能力存在於**兩個位置**：整台 Mac（`~/.codex`、`~/.claude`）與你開啟的專案。Orbita **同時呈現兩者**，讓你隨時清楚某個 Agent 在這裡到底看得到什麼。",
        "onboarding.body.agents": "每個分頁是**某個 Agent 的視角**。切換分頁**不會改動任何檔案**——只是對同一次掃描重新篩選，方便你對比 Codex、Claude Code、Trae 各自載入了什麼。",
        "onboarding.body.organize": "依類型篩選，依名稱或日期排序，並依**生效狀態**分區查看——已啟用、已停用、已探索。分組會讓外掛的子能力保持在一起。",
        "onboarding.body.actions": "三個動作，三種含義。**點一下卡片**看看各自做什麼——一個隱藏、一個複製、一個移除。",
        "onboarding.body.ready": "從側邊欄開啟一個專案即可開始。你可以隨時在**「設定 → 引導」**中**重看本引導**。",
        "onboarding.progress.step": "第 %d / %d 步",
        "onboarding.button.skip": "跳過",
        "onboarding.button.back": "上一步",
        "onboarding.button.getStarted": "開始使用",
        "onboarding.button.next": "下一步",
        "onboarding.language.chinese": "中文",
        "onboarding.language.help": "語言",
        "onboarding.illustration.welcome": "一排能力類型",
        "onboarding.scope.thisMac": "本機",
        "onboarding.scope.project": "專案",
        "onboarding.illustration.scope": "專案作用域嵌套在本機之中",
        "onboarding.illustration.agents": "四個 Agent 分頁篩選同一批能力",
        "onboarding.organize.filter.all": "全部",
        "onboarding.organize.section.enabled": "已啟用",
        "onboarding.organize.section.disabled": "已停用",
        "onboarding.illustration.organize": "能力依狀態篩選、排序與分組",
        "onboarding.action.disable.title": "停用",
        "onboarding.action.disable.detail": "在此隱藏。來源被快取，可完全還原。",
        "onboarding.action.fork.detail": "複製到另一個 Agent 自己的目錄。",
        "onboarding.action.delete.title": "刪除",
        "onboarding.action.delete.detail": "徹底移除該能力。",
        "onboarding.illustration.actions": "停用即隱藏，Fork 即複製，刪除即移除",
        "onboarding.ready.openProject": "開啟一個專案即可開始",
        "onboarding.illustration.ready": "設定完成",
        "permission.denied.noProbes": "Orbita 無法驗證對受保護的 macOS 資料夾的存取權限。如果你剛剛啟用了「完整磁碟存取權」，請結束並重新開啟 Orbita。",
        "permission.denied.notYet": "Orbita 尚無法驗證「完整磁碟存取權」。請授予「完整磁碟存取權」，然後結束並重新開啟 Orbita。",
        "permission.title": "Orbita 需要「完整磁碟存取權」",
        "permission.subtitle.reads": "Orbita 會讀取本機 Coding Agent 目錄，例如 ~/.agents、~/.codex、~/.claude，以及專案工作區、套件快取和鎖定檔。請在使用本應用程式前啟用「完整磁碟存取權」。",
        "permission.subtitle.skip": "如果你略過，Orbita 會預先檢查它即將掃描的確切使用者路徑和專案路徑，以便 macOS 在工作區開啟前彈出權限提示。",
        "permission.step1.title": "開啟「隱私權與安全性」",
        "permission.step1.detail": "點擊下方按鈕開啟「系統設定」。",
        "permission.step2.title": "啟用 Orbita",
        "permission.step2.detail": "進入「完整磁碟存取權」並開啟 Orbita 開關。如果列表中沒有 Orbita，請手動加入該應用程式。",
        "permission.step3.title": "結束並重新開啟 Orbita",
        "permission.step3.detail": "macOS 會在應用程式下次啟動時套用此權限。",
        "permission.button.openSettings": "開啟「系統設定」",
        "permission.button.checking": "正在檢查存取權限",
        "permission.button.skip": "略過並繼續",
        "permission.button.quit": "結束 Orbita",
        "app.access.stillCannotRead": "Orbita 仍無法讀取 %@。請允許 macOS 彈出的授權提示,然後重試,或開啟「完整磁碟取用權限」。",
        "app.access.requiredFolder": "某個必要的資料夾",
        "app.error.deleteCommandFailed": "刪除指令失敗:%@",
        "apply.success.clean": "已清理工作區。",
        "apply.success.delete": "已刪除 %@ 項。",
        "apply.success.disable": "已停用 %@ 項。",
        "apply.success.enable": "已啟用 %@ 項。",
        "apply.success.merge": "已合併工作區。",
        "apply.success.rollback": "已回滾。",
        "app.section.itemCount": "%d 項",
        "app.section.enabled": "已啟用",
        "app.section.disabled": "已停用",
        "app.subsection.other": "其他",
        "app.confirm.deleteTitle": "刪除 %@?",
        "app.confirm.disableTitle": "停用 %@?",
        "app.confirm.deleteCurrent": "刪除目前項目",
        "app.confirm.disableCurrent": "停用目前項目",
        "app.confirm.alsoDeleteSymlinks": "這還會一併刪除指向 %@ 的關聯符號連結。確認刪除?",
        "app.confirm.deleteSourceWithSymlinks": "這將永久刪除目前能力來源%@。%@ 是指向該來源的符號連結,將一併刪除以避免連結失效。",
        "app.confirm.deleteSelectionGrouped": "這將永久刪除目前所選項目%@,包括 %d 個分組內的能力來源。",
        "app.confirm.deleteSource": "這將永久刪除目前能力來源%@。",
        "app.confirm.disableSelectionGrouped": "這將停用目前所選項目%@,包括 %d 個分組內的能力來源。",
        "app.confirm.disableSource": "這將停用目前能力來源%@。",
        "app.confirm.disableCacheAndSymlink": "%@ 符號連結僅作為連結被移除。由於該主機沒有原生停用機制,真實檔案會被移入 Orbita 的停用儲存區(作用域對應:專案來源置於 .orbita/disabled,使用者來源置於 ~/.orbita/disabled),啟用時再移回原處。",
        "app.confirm.disableCache": "%@ 由於該主機沒有原生停用機制,真實檔案會被移入 Orbita 的停用儲存區(作用域對應:專案來源置於 .orbita/disabled,使用者來源置於 ~/.orbita/disabled),啟用時再移回原處。",
        "app.confirm.disableSymlinkOnly": "%@ 符號連結僅作為連結被移除;其指向的目標保持不變。",
        "app.confirm.disableIntent": "%@ Orbita 會在 .agents 中記錄停用意圖。",
        "app.confirm.forAgentSuffix": "(用於 %@)",
        "settings.title": "設定",
        "settings.close": "關閉設定",
        "settings.page.general": "一般",
        "settings.page.plugins": "外掛",
        "settings.page.release": "發佈",

        "settings.general.subtitle": "掃描行為、語言和能力顯示偏好。",
        "settings.general.preferences": "偏好設定",
        "settings.general.refresh.title": "重新整理",
        "settings.general.refresh.subtitle": "控制 Orbita 重新掃描能力前的快取有效期。",
        "settings.general.sort.title": "能力排序",
        "settings.general.sort.subtitle": "能力列表和分組區塊的預設排序。",
        "settings.general.language.title": "語言",
        "settings.general.language.subtitle": "Orbita 介面使用的顯示語言。",
        "settings.general.language.picker": "顯示語言",

        "settings.plugins.subtitle": "Codex、Claude Code 和 .agents 技能的維護指令。",
        "settings.plugins.maintenance": "維護",
        "settings.plugins.codex.title": "Codex 市集",
        "settings.plugins.codex.detail": "重新整理已設定的 Git 市集快照,並重新掃描 Orbita。",
        "settings.plugins.claude.title": "Claude Code 外掛",
        "settings.plugins.claude.detail": "列出已安裝的外掛及啟用狀態。可在檢視器中個別更新外掛。",
        "settings.plugins.agents.title": ".agents 技能",
        "settings.plugins.agents.detail": "在目前的專案上下文中觸發 Skills CLI 更新。",

        "settings.release.subtitle": "版本中繼資料、簽署 DMG 發佈、公證以及 Sparkle 就緒狀態。",
        "settings.release.pipeline": "流水線",
        "settings.release.group.build": "建置與 CI",
        "settings.release.group.trust": "簽署與公證",
        "settings.release.group.update": "自動更新",
        "settings.release.actions": "操作",
        "settings.release.action.gh.title": "檢查 GitHub CLI",
        "settings.release.action.gh.detail": "在建立標籤或發佈前,驗證本機 gh 認證狀態。",
        "settings.release.action.tag.title": "標記目前版本",
        "settings.release.action.tag.detail": "本機建立 DMG,推送發佈標籤,由 GitHub Actions 完成簽署、公證、裝訂並發佈 DMG。",
        "settings.release.row.workflow": "工作流",
        "settings.release.row.tag": "標籤",
        "settings.release.row.artifact": "產物",
        "settings.release.row.signing": "簽署",
        "settings.release.row.runtime": "執行階段",
        "settings.release.row.notary": "公證",
        "settings.release.row.updater": "更新器",
        "settings.release.row.feed": "Feed",
        "settings.release.row.security": "安全性",
        "settings.release.row.bundle": "Bundle",
        "settings.release.row.project": "專案",
        "settings.release.row.path": "路徑",

        "settings.command.output": "指令輸出",
        "settings.command.failed": "指令失敗",
        "settings.command.empty": "(無輸出)",
        "settings.command.run": "執行",
        "settings.command.running": "執行中",

        "refresh.thirtyMinutes": "30 分鐘",
        "refresh.oneHour": "1 小時",
        "refresh.automatic": "自動",
        "refresh.manual": "手動",
        "refresh.explain.thirtyMinutes": "快取結果超過 30 分鐘後自動重新掃描。",
        "refresh.explain.oneHour": "快取結果超過 1 小時後自動重新掃描。",
        "refresh.explain.automatic": "由 Orbita 自動決定：專案快取約 30 分鐘後、「這台 Mac」約 1 小時後重新掃描。",
        "refresh.explain.manual": "不會自動重新掃描，僅在你點擊「重新整理」時才掃描。",

        "sort.name": "名稱",
        "sort.modifiedNewest": "最近修改優先",
        "sort.modifiedOldest": "最早修改優先",
        "sort.statusPriority": "狀態（問題優先）",
        "sort.riskLevel": "風險（最高優先）",

        "group.prefix.subtitle": "前綴為 %@-* 彙整的內容",
        "hook.timing": "Hook 時機",
        "hook.timing.format": "Hook %@ 時機",

        "settings.page.guide": "引導",
        "settings.guide.subtitle": "快速上手引導，以及它的顯示時機。",
        "settings.guide.card": "快速上手",
        "settings.guide.replay.title": "重看引導",
        "settings.guide.replay.subtitle": "重新觀看關於作用域、Agent 分頁與核心操作的圖文引導。",
        "settings.guide.replay.button": "顯示引導",
        "settings.guide.frequency.title": "啟動時顯示",
        "settings.guide.frequency.subtitle": "「僅首次」為正常模式。「每次啟動」和「從不」是除錯用選項，方便無需重裝即可反覆查看引導。",
        "settings.guide.frequency.firstLaunch": "僅首次",
        "settings.guide.frequency.always": "每次啟動",
        "settings.guide.frequency.never": "從不",

        "toast.comingSoon": "敬請期待"
    ]
}
